language: node_js

services:
  - docker

before_install:
  - docker build -t thilina01/tms:latest -t thilina01/tms:0.0.1 .
  - docker run --rm -d thilina01/tms:0.0.1
  - docker ps -a

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change
